#!/bin/bash.rc

sudo apt update && sudo apt -y upgrade && sudo apt -y install firefox gcc gimp gnome-tweak-tool gnome-shell-extensions neofetch net-tools fish gparted thunderbird vlc python3 python3-pip dconf-editor flatpak wget qpdfview signal-desktop stacer && sudo snap install discord &&
#LibreOffice
flatpak install flathub org.libreoffice.LibreOffice
#Teams
sudo wget https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.3.00.5153_amd64.deb && apt install ./teams_1.3.00.5153_amd64.deb && rm ./teams_1.3.00.5153_amd64.dev
#Fonts LibreOffice
sudo apt-get install ttf-mscorefonts-installer && wget -qO- http://plasmasturm.org/dl/vistafonts-... | bash
#VSCode

#MISSING: vscode; dracula themes; MS teams; Libre office + fonts
#Maybe print something after done.
#LibreOffice flatpak install????
#Set fish as standard shell
#apt list --manual-installed
#sudo apt install texlive-latex-extra

#https://www.tecmint.com/install-visual-studio-code-on-linux/

#https://linuxize.com/post/how-to-install-visual-studio-code-on-ubuntu-20-04/

#https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-programming-environment-on-an-ubuntu-20-04-server
